name: Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit semgrep

      - name: Run flake8 (code style)
        run: |
          flake8 dojo --exit-zero --statistics > flake8-report.txt

      - name: Run Bandit (static code analysis)
        run: |
          bandit -r dojo -f txt -o bandit-report.txt

      - name: Run Semgrep (SAST)
        run: |
          semgrep --config=auto . --json > semgrep-report.json || true

      - name: Run GitLeaks (check for secrets)
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          ./gitleaks detect --source . --report-format json --report-path gitleaks-report.json || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            flake8-report.txt
            bandit-report.txt
            semgrep-report.json
